[package]
name = "example"
version = "0.5.0"
edition = "2021"

[dependencies]
winit = "0.28.1"
wgpu = "0.18.0"
futures = "0.3"
bytemuck = { version = "1.13", features = [ "derive" ] }
memoffset = "0.8.0"

[build-dependencies]
wgsl_to_wgpu = { path = "../wgsl_to_wgpu" }
