[workspace]
# wgpu requires the newer resolver
resolver = "2"
members = ["wgsl_to_wgpu", "example", "wgsl_to_wgpu/test_compile"]

[workspace.package]
edition = "2024"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
