[package]
name = "wgsl_to_wgpu"
version = "0.3.1"
authors = ["ScanMountGoat <>"]
description = "Generate typesafe Rust bindings for wgsl shaders in wgpu"
license = "MIT"
documentation = "https://docs.rs/wgsl_to_wgpu"
repository = "https://github.com/ScanMountGoat/wgsl_to_wgpu"
readme = "../README.md"
edition = "2021"

[dependencies]
naga = { version = "0.10.0", features = ["wgsl-in"] }
wgpu-types = "0.14.0"
syn = "1.0"
quote = "1.0"
proc-macro2 = "1"
prettyplease = "0.1.15"
thiserror = "1"

[dev-dependencies]
indoc = "1.0"
pretty_assertions = "1.2.1"
